### ISSUE TITLE
ticking entity

### ISSUE THREAD

**Issue by Alonlystalker** [McModded114/Extra-Attributes#1]
[crash-2023-08-01_09.32.40-client.txt](https://github.com/McModded114/Extra-Attributes/files/12225358/crash-2023-08-01_09.32.40-client.txt)

**Comment by Alonlystalker** [comment]
i think mcreator make a mess with custom arrows and onhit procedures.

**Comment by McModded114** [comment]
Should be fixed in 1.4. Will be out within an hour.
